# Generated by Django 4.0 on 2022-09-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of your sticker', max_length=50)),
                ('background_color', models.CharField(choices=[('red', 'Red'), ('pink', 'Pink'), ('black', 'Black')], default='white', max_length=50)),
                ('background_pattern', models.URLField(blank=True, choices=[('argyle', 'Argyle'), ('stripes', 'Stripes')], default='', max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=100, null=True)),
                ('font', models.CharField(choices=[('ms+madi', 'Ms+Madi'), ('josefin+sans', 'Josefin+Sans'), ('dosis', 'Dosis'), ('dangrek', 'Dangrek'), ('dancing+script', 'Dancing+Script'), ('eb+garamond', 'EB+Garamond'), ('lobster', 'Lobster'), ('pacifico', 'Pacifico')], default='pacifico', max_length=50)),
                ('font_color', models.CharField(choices=[('red', 'Red'), ('pink', 'Pink'), ('black', 'Black')], default='black', max_length=50)),
                ('message', models.CharField(blank=True, help_text='enter your message here', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='stickers.customuser')),
            ],
        ),
    ]
