# Generated by Django 4.0 on 2022-09-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followed',
        ),
    ]
