# Generated by Django 4.0 on 2022-09-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_remove_follow_followed_remove_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='background_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('fuschia', 'Fuschia'), ('pink', 'Pink'), ('orange', 'Orange')], default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='font',
            field=models.CharField(choices=[('dancing+script', 'Dancing+Script'), ('dangrek', 'Dangrek'), ('dosis', 'Dosis'), ('eb+garamond', 'EB+Garamond'), ('josefin+sans', 'Josefin+Sans'), ('lobster', 'Lobster'), ('ms+madi', 'Ms+Madi'), ('pacifico', 'Pacifico')], default='pacifico', max_length=50),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='font_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('fuschia', 'Fuschia'), ('pink', 'Pink'), ('orange', 'Orange')], default='black', max_length=50),
        ),
    ]
