# Generated by Django 4.0 on 2022-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_alter_sticker_background_color_alter_sticker_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='background_pattern',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='image',
        ),
        migrations.AddField(
            model_name='sticker',
            name='image_url',
            field=models.URLField(blank=True, choices=[('https://media.istockphoto.com/photos/donut-with-sprinkles-isolated-picture-id538335769?k=20&m=538335769&s=612x612&w=0&h=A1DAZd6aHjfRyq2qKAKuBD9KAf0cq1LXKW8mpvTxKgU=', 'donut'), ('https://cdn.pixabay.com/photo/2015/04/19/08/33/flower-729512__340.jpg', 'flower'), ('https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/shutterstock_1512536354.jpg?crop=0%2C317%2C2664%2C1465&wid=4000&hei=2200&scl=0.666', 'butterfly'), ('http://cdn.shopify.com/s/files/1/0641/1521/products/patches-smiley-face-happy-sad-venn.jpg?v=1613156051', 'happy-sad-face'), ('https://img.freepik.com/free-vector/ice-cream-cone-cartoon-icon-illustration-sweet-food-icon-concept-isolated-flat-cartoon-style_138676-2924.jpg?w=360', 'ice-cream'), ('https://illustoon.com/photo/4292.png', 'thumbs-up'), ('https://www.pngitem.com/pimgs/m/595-5957528_black-heart-symbol-outline-love-heart-png-transparent.png', 'heart')], null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='pattern_url',
            field=models.URLField(blank=True, choices=[('https://www.transparenttextures.com/patterns/black-thread.png', 'black-thread'), ('https://www.transparenttextures.com/patterns/bo-play.png', 'bo-play'), ('https://www.transparenttextures.com/patterns/brick-wall.png', 'brick-wall'), ('https://www.transparenttextures.com/patterns/clean-textile.png', 'clean-textile'), ('https://www.transparenttextures.com/patterns/crisp-paper-ruffles.png', 'crisp-paper-ruffles'), ('https://www.transparenttextures.com/patterns/cutcube.png', 'cutcube'), ('https://www.transparenttextures.com/patterns/diagmonds-light.png', 'diagmonds-light'), ('https://www.transparenttextures.com/patterns/dimension.png', 'dimensions')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='font',
            field=models.CharField(choices=[('dangrek', 'Dangrek'), ('dancing+script', 'Dancing+Script'), ('dosis', 'Dosis'), ('eb+garamond', 'EB+Garamond'), ('josefin+sans', 'Josefin+Sans'), ('lobster', 'Lobster'), ('ms+madi', 'Ms+Madi'), ('pacifico', 'Pacifico')], default='pacifico', max_length=50),
        ),
    ]
