# Generated by Django 4.0 on 2022-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_alter_sticker_background_color_alter_sticker_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='background_pattern',
            field=models.URLField(blank=True, choices=[('https://www.transparenttextures.com/patterns/black-thread.png', 'black-thread'), ('https://www.transparenttextures.com/patterns/bo-play.png', 'bo-play'), ('https://www.transparenttextures.com/patterns/brick-wall.png', 'brick-wall'), ('https://www.transparenttextures.com/patterns/clean-textile.png', 'clean-textile'), ('https://www.transparenttextures.com/patterns/crisp-paper-ruffles.png', 'crisp-paper-ruffles'), ('https://www.transparenttextures.com/patterns/cutcube.png', 'cutcube'), ('https://www.transparenttextures.com/patterns/diagmonds-light.png', 'diagmonds-light'), ('https://www.transparenttextures.com/patterns/dimension.png', 'dimensions')], default='', max_length=100, null=True),
        ),
    ]
