# Generated by Django 4.0 on 2022-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0007_rename_name_sticker_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='background_pattern',
            field=models.URLField(blank=True, choices=[], default='', max_length=100, null=True),
        ),
    ]
