# Generated by Django 4.0 on 2022-09-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_sticker_background_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='background_pattern',
        ),
    ]
