# Generated by Django 4.0 on 2022-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_follow_unique-follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='background_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange')], default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='font_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange')], default='black', max_length=50),
        ),
    ]
